# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'mobile-lab' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for mobile-lab

  pod "Alamofire"

  target 'mobile-labTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'mobile-labUITests' do
    # Pods for testing
  end

end
